// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/rpc/proto/hand.proto

package handpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespondEvent_Type int32

const (
	RespondEvent_TYPE_UNSPECIFIED RespondEvent_Type = 0
	RespondEvent_TEXT_DELTA       RespondEvent_Type = 1
	RespondEvent_DONE             RespondEvent_Type = 2
	RespondEvent_ERROR            RespondEvent_Type = 3
	RespondEvent_TRACE_EVENT      RespondEvent_Type = 4
)

// Enum value maps for RespondEvent_Type.
var (
	RespondEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TEXT_DELTA",
		2: "DONE",
		3: "ERROR",
		4: "TRACE_EVENT",
	}
	RespondEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TEXT_DELTA":       1,
		"DONE":             2,
		"ERROR":            3,
		"TRACE_EVENT":      4,
	}
)

func (x RespondEvent_Type) Enum() *RespondEvent_Type {
	p := new(RespondEvent_Type)
	*p = x
	return p
}

func (x RespondEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespondEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_rpc_proto_hand_proto_enumTypes[0].Descriptor()
}

func (RespondEvent_Type) Type() protoreflect.EnumType {
	return &file_internal_rpc_proto_hand_proto_enumTypes[0]
}

func (x RespondEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespondEvent_Type.Descriptor instead.
func (RespondEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{1, 0}
}

type RespondEvent_Channel int32

const (
	RespondEvent_CHANNEL_UNSPECIFIED RespondEvent_Channel = 0
	RespondEvent_ASSISTANT           RespondEvent_Channel = 1
	RespondEvent_REASONING           RespondEvent_Channel = 2
)

// Enum value maps for RespondEvent_Channel.
var (
	RespondEvent_Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "ASSISTANT",
		2: "REASONING",
	}
	RespondEvent_Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"ASSISTANT":           1,
		"REASONING":           2,
	}
)

func (x RespondEvent_Channel) Enum() *RespondEvent_Channel {
	p := new(RespondEvent_Channel)
	*p = x
	return p
}

func (x RespondEvent_Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespondEvent_Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_rpc_proto_hand_proto_enumTypes[1].Descriptor()
}

func (RespondEvent_Channel) Type() protoreflect.EnumType {
	return &file_internal_rpc_proto_hand_proto_enumTypes[1]
}

func (x RespondEvent_Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespondEvent_Channel.Descriptor instead.
func (RespondEvent_Channel) EnumDescriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{1, 1}
}

type RepairSessionRequest_Type int32

const (
	RepairSessionRequest_TYPE_UNSPECIFIED RepairSessionRequest_Type = 0
	RepairSessionRequest_VECTOR           RepairSessionRequest_Type = 1
)

// Enum value maps for RepairSessionRequest_Type.
var (
	RepairSessionRequest_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "VECTOR",
	}
	RepairSessionRequest_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"VECTOR":           1,
	}
)

func (x RepairSessionRequest_Type) Enum() *RepairSessionRequest_Type {
	p := new(RepairSessionRequest_Type)
	*p = x
	return p
}

func (x RepairSessionRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepairSessionRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_rpc_proto_hand_proto_enumTypes[2].Descriptor()
}

func (RepairSessionRequest_Type) Type() protoreflect.EnumType {
	return &file_internal_rpc_proto_hand_proto_enumTypes[2]
}

func (x RepairSessionRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepairSessionRequest_Type.Descriptor instead.
func (RepairSessionRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{19, 0}
}

type RespondRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Instruct      string                 `protobuf:"bytes,2,opt,name=instruct,proto3" json:"instruct,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Stream        *bool                  `protobuf:"varint,4,opt,name=stream,proto3,oneof" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondRequest) Reset() {
	*x = RespondRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondRequest) ProtoMessage() {}

func (x *RespondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondRequest.ProtoReflect.Descriptor instead.
func (*RespondRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{0}
}

func (x *RespondRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RespondRequest) GetInstruct() string {
	if x != nil {
		return x.Instruct
	}
	return ""
}

func (x *RespondRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RespondRequest) GetStream() bool {
	if x != nil && x.Stream != nil {
		return *x.Stream
	}
	return false
}

type RespondEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             RespondEvent_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=hand.v1.RespondEvent_Type" json:"type,omitempty"`
	Text             string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Error            string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Channel          RespondEvent_Channel   `protobuf:"varint,4,opt,name=channel,proto3,enum=hand.v1.RespondEvent_Channel" json:"channel,omitempty"`
	TraceType        string                 `protobuf:"bytes,5,opt,name=trace_type,json=traceType,proto3" json:"trace_type,omitempty"`
	TracePayloadJson string                 `protobuf:"bytes,6,opt,name=trace_payload_json,json=tracePayloadJson,proto3" json:"trace_payload_json,omitempty"`
	// Present for TRACE_EVENT, ERROR, and DONE. TEXT_DELTA consumers should use local receive time.
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TraceSessionId string                 `protobuf:"bytes,8,opt,name=trace_session_id,json=traceSessionId,proto3" json:"trace_session_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RespondEvent) Reset() {
	*x = RespondEvent{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondEvent) ProtoMessage() {}

func (x *RespondEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondEvent.ProtoReflect.Descriptor instead.
func (*RespondEvent) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{1}
}

func (x *RespondEvent) GetType() RespondEvent_Type {
	if x != nil {
		return x.Type
	}
	return RespondEvent_TYPE_UNSPECIFIED
}

func (x *RespondEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RespondEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RespondEvent) GetChannel() RespondEvent_Channel {
	if x != nil {
		return x.Channel
	}
	return RespondEvent_CHANNEL_UNSPECIFIED
}

func (x *RespondEvent) GetTraceType() string {
	if x != nil {
		return x.TraceType
	}
	return ""
}

func (x *RespondEvent) GetTracePayloadJson() string {
	if x != nil {
		return x.TracePayloadJson
	}
	return ""
}

func (x *RespondEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RespondEvent) GetTraceSessionId() string {
	if x != nil {
		return x.TraceSessionId
	}
	return ""
}

type SessionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,2,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	MessageCount  int32                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	TitleSource   string                 `protobuf:"bytes,5,opt,name=title_source,json=titleSource,proto3" json:"title_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{2}
}

func (x *SessionSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionSummary) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *SessionSummary) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SessionSummary) GetTitleSource() string {
	if x != nil {
		return x.TitleSource
	}
	return ""
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AutoSwitch    *bool                  `protobuf:"varint,2,opt,name=auto_switch,json=autoSwitch,proto3,oneof" json:"auto_switch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSessionRequest) GetAutoSwitch() bool {
	if x != nil && x.AutoSwitch != nil {
		return *x.AutoSwitch
	}
	return false
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionSummary        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionResponse) GetSession() *SessionSummary {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{5}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSummary      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsResponse) GetSessions() []*SessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type UseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseSessionRequest) Reset() {
	*x = UseSessionRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseSessionRequest) ProtoMessage() {}

func (x *UseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseSessionRequest.ProtoReflect.Descriptor instead.
func (*UseSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{7}
}

func (x *UseSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseSessionResponse) Reset() {
	*x = UseSessionResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseSessionResponse) ProtoMessage() {}

func (x *UseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseSessionResponse.ProtoReflect.Descriptor instead.
func (*UseSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{8}
}

func (x *UseSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArchiveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveSessionRequest) Reset() {
	*x = ArchiveSessionRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveSessionRequest) ProtoMessage() {}

func (x *ArchiveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveSessionRequest.ProtoReflect.Descriptor instead.
func (*ArchiveSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{9}
}

func (x *ArchiveSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArchiveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveSessionResponse) Reset() {
	*x = ArchiveSessionResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveSessionResponse) ProtoMessage() {}

func (x *ArchiveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveSessionResponse.ProtoReflect.Descriptor instead.
func (*ArchiveSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{10}
}

func (x *ArchiveSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnarchiveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveSessionRequest) Reset() {
	*x = UnarchiveSessionRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveSessionRequest) ProtoMessage() {}

func (x *UnarchiveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveSessionRequest.ProtoReflect.Descriptor instead.
func (*UnarchiveSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{11}
}

func (x *UnarchiveSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnarchiveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionSummary        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveSessionResponse) Reset() {
	*x = UnarchiveSessionResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveSessionResponse) ProtoMessage() {}

func (x *UnarchiveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveSessionResponse.ProtoReflect.Descriptor instead.
func (*UnarchiveSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{12}
}

func (x *UnarchiveSessionResponse) GetSession() *SessionSummary {
	if x != nil {
		return x.Session
	}
	return nil
}

type RenameSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSessionRequest) Reset() {
	*x = RenameSessionRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionRequest) ProtoMessage() {}

func (x *RenameSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionRequest.ProtoReflect.Descriptor instead.
func (*RenameSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{13}
}

func (x *RenameSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RenameSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionSummary        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSessionResponse) Reset() {
	*x = RenameSessionResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionResponse) ProtoMessage() {}

func (x *RenameSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionResponse.ProtoReflect.Descriptor instead.
func (*RenameSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{14}
}

func (x *RenameSessionResponse) GetSession() *SessionSummary {
	if x != nil {
		return x.Session
	}
	return nil
}

type CurrentSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentSessionRequest) Reset() {
	*x = CurrentSessionRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentSessionRequest) ProtoMessage() {}

func (x *CurrentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentSessionRequest.ProtoReflect.Descriptor instead.
func (*CurrentSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{15}
}

type CurrentSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TitleSource   string                 `protobuf:"bytes,3,opt,name=title_source,json=titleSource,proto3" json:"title_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentSessionResponse) Reset() {
	*x = CurrentSessionResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentSessionResponse) ProtoMessage() {}

func (x *CurrentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentSessionResponse.ProtoReflect.Descriptor instead.
func (*CurrentSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{16}
}

func (x *CurrentSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CurrentSessionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CurrentSessionResponse) GetTitleSource() string {
	if x != nil {
		return x.TitleSource
	}
	return ""
}

type CompactSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactSessionRequest) Reset() {
	*x = CompactSessionRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactSessionRequest) ProtoMessage() {}

func (x *CompactSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactSessionRequest.ProtoReflect.Descriptor instead.
func (*CompactSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{17}
}

func (x *CompactSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CompactSessionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceEndOffset      int32                  `protobuf:"varint,2,opt,name=source_end_offset,json=sourceEndOffset,proto3" json:"source_end_offset,omitempty"`
	SourceMessageCount   int32                  `protobuf:"varint,3,opt,name=source_message_count,json=sourceMessageCount,proto3" json:"source_message_count,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CurrentContextLength int32                  `protobuf:"varint,5,opt,name=current_context_length,json=currentContextLength,proto3" json:"current_context_length,omitempty"`
	TotalContextLength   int32                  `protobuf:"varint,6,opt,name=total_context_length,json=totalContextLength,proto3" json:"total_context_length,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CompactSessionResponse) Reset() {
	*x = CompactSessionResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactSessionResponse) ProtoMessage() {}

func (x *CompactSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactSessionResponse.ProtoReflect.Descriptor instead.
func (*CompactSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{18}
}

func (x *CompactSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompactSessionResponse) GetSourceEndOffset() int32 {
	if x != nil {
		return x.SourceEndOffset
	}
	return 0
}

func (x *CompactSessionResponse) GetSourceMessageCount() int32 {
	if x != nil {
		return x.SourceMessageCount
	}
	return 0
}

func (x *CompactSessionResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CompactSessionResponse) GetCurrentContextLength() int32 {
	if x != nil {
		return x.CurrentContextLength
	}
	return 0
}

func (x *CompactSessionResponse) GetTotalContextLength() int32 {
	if x != nil {
		return x.TotalContextLength
	}
	return 0
}

type RepairSessionRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          RepairSessionRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=hand.v1.RepairSessionRequest_Type" json:"type,omitempty"`
	Vector        *VectorRepairOption       `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairSessionRequest) Reset() {
	*x = RepairSessionRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairSessionRequest) ProtoMessage() {}

func (x *RepairSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairSessionRequest.ProtoReflect.Descriptor instead.
func (*RepairSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{19}
}

func (x *RepairSessionRequest) GetType() RepairSessionRequest_Type {
	if x != nil {
		return x.Type
	}
	return RepairSessionRequest_TYPE_UNSPECIFIED
}

func (x *RepairSessionRequest) GetVector() *VectorRepairOption {
	if x != nil {
		return x.Vector
	}
	return nil
}

type RepairSessionResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          RepairSessionRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=hand.v1.RepairSessionRequest_Type" json:"type,omitempty"`
	Vector        *VectorRepairResponse     `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairSessionResponse) Reset() {
	*x = RepairSessionResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairSessionResponse) ProtoMessage() {}

func (x *RepairSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairSessionResponse.ProtoReflect.Descriptor instead.
func (*RepairSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{20}
}

func (x *RepairSessionResponse) GetType() RepairSessionRequest_Type {
	if x != nil {
		return x.Type
	}
	return RepairSessionRequest_TYPE_UNSPECIFIED
}

func (x *RepairSessionResponse) GetVector() *VectorRepairResponse {
	if x != nil {
		return x.Vector
	}
	return nil
}

type VectorRepairOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Full          bool                   `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorRepairOption) Reset() {
	*x = VectorRepairOption{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorRepairOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorRepairOption) ProtoMessage() {}

func (x *VectorRepairOption) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorRepairOption.ProtoReflect.Descriptor instead.
func (*VectorRepairOption) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{21}
}

func (x *VectorRepairOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorRepairOption) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

type VectorRepairResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionsScanned int32                  `protobuf:"varint,1,opt,name=sessions_scanned,json=sessionsScanned,proto3" json:"sessions_scanned,omitempty"`
	MessagesScanned int32                  `protobuf:"varint,2,opt,name=messages_scanned,json=messagesScanned,proto3" json:"messages_scanned,omitempty"`
	RowsScanned     int32                  `protobuf:"varint,3,opt,name=rows_scanned,json=rowsScanned,proto3" json:"rows_scanned,omitempty"`
	MissingRows     int32                  `protobuf:"varint,4,opt,name=missing_rows,json=missingRows,proto3" json:"missing_rows,omitempty"`
	StaleRows       int32                  `protobuf:"varint,5,opt,name=stale_rows,json=staleRows,proto3" json:"stale_rows,omitempty"`
	UnchangedRows   int32                  `protobuf:"varint,6,opt,name=unchanged_rows,json=unchangedRows,proto3" json:"unchanged_rows,omitempty"`
	RebuiltRows     int32                  `protobuf:"varint,7,opt,name=rebuilt_rows,json=rebuiltRows,proto3" json:"rebuilt_rows,omitempty"`
	DeletedSources  int32                  `protobuf:"varint,8,opt,name=deleted_sources,json=deletedSources,proto3" json:"deleted_sources,omitempty"`
	Batches         int32                  `protobuf:"varint,9,opt,name=batches,proto3" json:"batches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VectorRepairResponse) Reset() {
	*x = VectorRepairResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorRepairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorRepairResponse) ProtoMessage() {}

func (x *VectorRepairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorRepairResponse.ProtoReflect.Descriptor instead.
func (*VectorRepairResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{22}
}

func (x *VectorRepairResponse) GetSessionsScanned() int32 {
	if x != nil {
		return x.SessionsScanned
	}
	return 0
}

func (x *VectorRepairResponse) GetMessagesScanned() int32 {
	if x != nil {
		return x.MessagesScanned
	}
	return 0
}

func (x *VectorRepairResponse) GetRowsScanned() int32 {
	if x != nil {
		return x.RowsScanned
	}
	return 0
}

func (x *VectorRepairResponse) GetMissingRows() int32 {
	if x != nil {
		return x.MissingRows
	}
	return 0
}

func (x *VectorRepairResponse) GetStaleRows() int32 {
	if x != nil {
		return x.StaleRows
	}
	return 0
}

func (x *VectorRepairResponse) GetUnchangedRows() int32 {
	if x != nil {
		return x.UnchangedRows
	}
	return 0
}

func (x *VectorRepairResponse) GetRebuiltRows() int32 {
	if x != nil {
		return x.RebuiltRows
	}
	return 0
}

func (x *VectorRepairResponse) GetDeletedSources() int32 {
	if x != nil {
		return x.DeletedSources
	}
	return 0
}

func (x *VectorRepairResponse) GetBatches() int32 {
	if x != nil {
		return x.Batches
	}
	return 0
}

type GetSessionStatusRequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusRequestContext) Reset() {
	*x = GetSessionStatusRequestContext{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusRequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusRequestContext) ProtoMessage() {}

func (x *GetSessionStatusRequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusRequestContext.ProtoReflect.Descriptor instead.
func (*GetSessionStatusRequestContext) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{23}
}

func (x *GetSessionStatusRequestContext) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSessionStatusRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Context       *GetSessionStatusRequestContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusRequest) Reset() {
	*x = GetSessionStatusRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusRequest) ProtoMessage() {}

func (x *GetSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{24}
}

func (x *GetSessionStatusRequest) GetContext() *GetSessionStatusRequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetSessionStatusResponse struct {
	state            protoimpl.MessageState            `protogen:"open.v1"`
	Id               string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Context          *GetSessionStatusResponse_Context `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Size             int32                             `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt        *timestamppb.Timestamp            `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp            `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompactionStatus string                            `protobuf:"bytes,6,opt,name=compaction_status,json=compactionStatus,proto3" json:"compaction_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSessionStatusResponse) Reset() {
	*x = GetSessionStatusResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusResponse) ProtoMessage() {}

func (x *GetSessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{25}
}

func (x *GetSessionStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSessionStatusResponse) GetContext() *GetSessionStatusResponse_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetSessionStatusResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetSessionStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetSessionStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetSessionStatusResponse) GetCompactionStatus() string {
	if x != nil {
		return x.CompactionStatus
	}
	return ""
}

type GetSessionTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageOffset int32                  `protobuf:"varint,2,opt,name=message_offset,json=messageOffset,proto3" json:"message_offset,omitempty"`
	MessageLimit  int32                  `protobuf:"varint,3,opt,name=message_limit,json=messageLimit,proto3" json:"message_limit,omitempty"`
	TraceOffset   int32                  `protobuf:"varint,4,opt,name=trace_offset,json=traceOffset,proto3" json:"trace_offset,omitempty"`
	TraceLimit    int32                  `protobuf:"varint,5,opt,name=trace_limit,json=traceLimit,proto3" json:"trace_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionTimelineRequest) Reset() {
	*x = GetSessionTimelineRequest{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTimelineRequest) ProtoMessage() {}

func (x *GetSessionTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetSessionTimelineRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{26}
}

func (x *GetSessionTimelineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSessionTimelineRequest) GetMessageOffset() int32 {
	if x != nil {
		return x.MessageOffset
	}
	return 0
}

func (x *GetSessionTimelineRequest) GetMessageLimit() int32 {
	if x != nil {
		return x.MessageLimit
	}
	return 0
}

func (x *GetSessionTimelineRequest) GetTraceOffset() int32 {
	if x != nil {
		return x.TraceOffset
	}
	return 0
}

func (x *GetSessionTimelineRequest) GetTraceLimit() int32 {
	if x != nil {
		return x.TraceLimit
	}
	return 0
}

type SessionTimelineToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTimelineToolCall) Reset() {
	*x = SessionTimelineToolCall{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTimelineToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTimelineToolCall) ProtoMessage() {}

func (x *SessionTimelineToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTimelineToolCall.ProtoReflect.Descriptor instead.
func (*SessionTimelineToolCall) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{27}
}

func (x *SessionTimelineToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionTimelineToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionTimelineToolCall) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type SessionTimelineMessage struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Offset        int32                      `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Id            uint64                     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                     `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Name          string                     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ToolCallId    string                     `protobuf:"bytes,5,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Content       string                     `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp     `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ToolCalls     []*SessionTimelineToolCall `protobuf:"bytes,8,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTimelineMessage) Reset() {
	*x = SessionTimelineMessage{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTimelineMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTimelineMessage) ProtoMessage() {}

func (x *SessionTimelineMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTimelineMessage.ProtoReflect.Descriptor instead.
func (*SessionTimelineMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{28}
}

func (x *SessionTimelineMessage) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SessionTimelineMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionTimelineMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionTimelineMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionTimelineMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *SessionTimelineMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SessionTimelineMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionTimelineMessage) GetToolCalls() []*SessionTimelineToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type SessionTimelineTraceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTimelineTraceEvent) Reset() {
	*x = SessionTimelineTraceEvent{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTimelineTraceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTimelineTraceEvent) ProtoMessage() {}

func (x *SessionTimelineTraceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTimelineTraceEvent.ProtoReflect.Descriptor instead.
func (*SessionTimelineTraceEvent) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{29}
}

func (x *SessionTimelineTraceEvent) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionTimelineTraceEvent) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SessionTimelineTraceEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SessionTimelineTraceEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SessionTimelineTraceEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type GetSessionTimelineResponse struct {
	state                 protoimpl.MessageState       `protogen:"open.v1"`
	Id                    string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Messages              []*SessionTimelineMessage    `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	TraceEvents           []*SessionTimelineTraceEvent `protobuf:"bytes,3,rep,name=trace_events,json=traceEvents,proto3" json:"trace_events,omitempty"`
	MessagesHasMore       bool                         `protobuf:"varint,4,opt,name=messages_has_more,json=messagesHasMore,proto3" json:"messages_has_more,omitempty"`
	TracesHasMore         bool                         `protobuf:"varint,5,opt,name=traces_has_more,json=tracesHasMore,proto3" json:"traces_has_more,omitempty"`
	TracesTruncatedBefore bool                         `protobuf:"varint,6,opt,name=traces_truncated_before,json=tracesTruncatedBefore,proto3" json:"traces_truncated_before,omitempty"`
	FirstTraceSequence    int32                        `protobuf:"varint,7,opt,name=first_trace_sequence,json=firstTraceSequence,proto3" json:"first_trace_sequence,omitempty"`
	LastTraceSequence     int32                        `protobuf:"varint,8,opt,name=last_trace_sequence,json=lastTraceSequence,proto3" json:"last_trace_sequence,omitempty"`
	Title                 string                       `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	TitleSource           string                       `protobuf:"bytes,10,opt,name=title_source,json=titleSource,proto3" json:"title_source,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSessionTimelineResponse) Reset() {
	*x = GetSessionTimelineResponse{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTimelineResponse) ProtoMessage() {}

func (x *GetSessionTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetSessionTimelineResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{30}
}

func (x *GetSessionTimelineResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSessionTimelineResponse) GetMessages() []*SessionTimelineMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetSessionTimelineResponse) GetTraceEvents() []*SessionTimelineTraceEvent {
	if x != nil {
		return x.TraceEvents
	}
	return nil
}

func (x *GetSessionTimelineResponse) GetMessagesHasMore() bool {
	if x != nil {
		return x.MessagesHasMore
	}
	return false
}

func (x *GetSessionTimelineResponse) GetTracesHasMore() bool {
	if x != nil {
		return x.TracesHasMore
	}
	return false
}

func (x *GetSessionTimelineResponse) GetTracesTruncatedBefore() bool {
	if x != nil {
		return x.TracesTruncatedBefore
	}
	return false
}

func (x *GetSessionTimelineResponse) GetFirstTraceSequence() int32 {
	if x != nil {
		return x.FirstTraceSequence
	}
	return 0
}

func (x *GetSessionTimelineResponse) GetLastTraceSequence() int32 {
	if x != nil {
		return x.LastTraceSequence
	}
	return 0
}

func (x *GetSessionTimelineResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetSessionTimelineResponse) GetTitleSource() string {
	if x != nil {
		return x.TitleSource
	}
	return ""
}

type GetSessionStatusResponse_Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Used          int32                  `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Remaining     int32                  `protobuf:"varint,4,opt,name=remaining,proto3" json:"remaining,omitempty"`
	UsedPct       float64                `protobuf:"fixed64,5,opt,name=used_pct,json=usedPct,proto3" json:"used_pct,omitempty"`
	RemainingPct  float64                `protobuf:"fixed64,6,opt,name=remaining_pct,json=remainingPct,proto3" json:"remaining_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusResponse_Context) Reset() {
	*x = GetSessionStatusResponse_Context{}
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusResponse_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusResponse_Context) ProtoMessage() {}

func (x *GetSessionStatusResponse_Context) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_hand_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusResponse_Context.ProtoReflect.Descriptor instead.
func (*GetSessionStatusResponse_Context) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_hand_proto_rawDescGZIP(), []int{25, 0}
}

func (x *GetSessionStatusResponse_Context) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetSessionStatusResponse_Context) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetSessionStatusResponse_Context) GetUsed() int32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *GetSessionStatusResponse_Context) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *GetSessionStatusResponse_Context) GetUsedPct() float64 {
	if x != nil {
		return x.UsedPct
	}
	return 0
}

func (x *GetSessionStatusResponse_Context) GetRemainingPct() float64 {
	if x != nil {
		return x.RemainingPct
	}
	return 0
}

var File_internal_rpc_proto_hand_proto protoreflect.FileDescriptor

const file_internal_rpc_proto_hand_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/rpc/proto/hand.proto\x12\ahand.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\x0eRespondRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\binstruct\x18\x02 \x01(\tR\binstruct\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1b\n" +
	"\x06stream\x18\x04 \x01(\bH\x00R\x06stream\x88\x01\x01B\t\n" +
	"\a_stream\"\xe8\x03\n" +
	"\fRespondEvent\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.hand.v1.RespondEvent.TypeR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x127\n" +
	"\achannel\x18\x04 \x01(\x0e2\x1d.hand.v1.RespondEvent.ChannelR\achannel\x12\x1d\n" +
	"\n" +
	"trace_type\x18\x05 \x01(\tR\ttraceType\x12,\n" +
	"\x12trace_payload_json\x18\x06 \x01(\tR\x10tracePayloadJson\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\x10trace_session_id\x18\b \x01(\tR\x0etraceSessionId\"R\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TEXT_DELTA\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\x0f\n" +
	"\vTRACE_EVENT\x10\x04\"@\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tASSISTANT\x10\x01\x12\r\n" +
	"\tREASONING\x10\x02\"\xa6\x01\n" +
	"\x0eSessionSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fupdated_at_unix\x18\x02 \x01(\x03R\rupdatedAtUnix\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x05R\fmessageCount\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12!\n" +
	"\ftitle_source\x18\x05 \x01(\tR\vtitleSource\"\\\n" +
	"\x14CreateSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\vauto_switch\x18\x02 \x01(\bH\x00R\n" +
	"autoSwitch\x88\x01\x01B\x0e\n" +
	"\f_auto_switch\"J\n" +
	"\x15CreateSessionResponse\x121\n" +
	"\asession\x18\x01 \x01(\v2\x17.hand.v1.SessionSummaryR\asession\"\x15\n" +
	"\x13ListSessionsRequest\"K\n" +
	"\x14ListSessionsResponse\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.hand.v1.SessionSummaryR\bsessions\"#\n" +
	"\x11UseSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12UseSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15ArchiveSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16ArchiveSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x17UnarchiveSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x18UnarchiveSessionResponse\x121\n" +
	"\asession\x18\x01 \x01(\v2\x17.hand.v1.SessionSummaryR\asession\"<\n" +
	"\x14RenameSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"J\n" +
	"\x15RenameSessionResponse\x121\n" +
	"\asession\x18\x01 \x01(\v2\x17.hand.v1.SessionSummaryR\asession\"\x17\n" +
	"\x15CurrentSessionRequest\"a\n" +
	"\x16CurrentSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\ftitle_source\x18\x03 \x01(\tR\vtitleSource\"'\n" +
	"\x15CompactSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa9\x02\n" +
	"\x16CompactSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11source_end_offset\x18\x02 \x01(\x05R\x0fsourceEndOffset\x120\n" +
	"\x14source_message_count\x18\x03 \x01(\x05R\x12sourceMessageCount\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x124\n" +
	"\x16current_context_length\x18\x05 \x01(\x05R\x14currentContextLength\x120\n" +
	"\x14total_context_length\x18\x06 \x01(\x05R\x12totalContextLength\"\xad\x01\n" +
	"\x14RepairSessionRequest\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".hand.v1.RepairSessionRequest.TypeR\x04type\x123\n" +
	"\x06vector\x18\x02 \x01(\v2\x1b.hand.v1.VectorRepairOptionR\x06vector\"(\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06VECTOR\x10\x01\"\x86\x01\n" +
	"\x15RepairSessionResponse\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".hand.v1.RepairSessionRequest.TypeR\x04type\x125\n" +
	"\x06vector\x18\x02 \x01(\v2\x1d.hand.v1.VectorRepairResponseR\x06vector\"8\n" +
	"\x12VectorRepairOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04full\x18\x02 \x01(\bR\x04full\"\xde\x02\n" +
	"\x14VectorRepairResponse\x12)\n" +
	"\x10sessions_scanned\x18\x01 \x01(\x05R\x0fsessionsScanned\x12)\n" +
	"\x10messages_scanned\x18\x02 \x01(\x05R\x0fmessagesScanned\x12!\n" +
	"\frows_scanned\x18\x03 \x01(\x05R\vrowsScanned\x12!\n" +
	"\fmissing_rows\x18\x04 \x01(\x05R\vmissingRows\x12\x1d\n" +
	"\n" +
	"stale_rows\x18\x05 \x01(\x05R\tstaleRows\x12%\n" +
	"\x0eunchanged_rows\x18\x06 \x01(\x05R\runchangedRows\x12!\n" +
	"\frebuilt_rows\x18\a \x01(\x05R\vrebuiltRows\x12'\n" +
	"\x0fdeleted_sources\x18\b \x01(\x05R\x0edeletedSources\x12\x18\n" +
	"\abatches\x18\t \x01(\x05R\abatches\"0\n" +
	"\x1eGetSessionStatusRequestContext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x17GetSessionStatusRequest\x12A\n" +
	"\acontext\x18\x01 \x01(\v2'.hand.v1.GetSessionStatusRequestContextR\acontext\"\xd4\x03\n" +
	"\x18GetSessionStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\acontext\x18\x02 \x01(\v2).hand.v1.GetSessionStatusResponse.ContextR\acontext\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12+\n" +
	"\x11compaction_status\x18\x06 \x01(\tR\x10compactionStatus\x1a\xab\x01\n" +
	"\aContext\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x05R\x04used\x12\x1c\n" +
	"\tremaining\x18\x04 \x01(\x05R\tremaining\x12\x19\n" +
	"\bused_pct\x18\x05 \x01(\x01R\ausedPct\x12#\n" +
	"\rremaining_pct\x18\x06 \x01(\x01R\fremainingPct\"\xbb\x01\n" +
	"\x19GetSessionTimelineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0emessage_offset\x18\x02 \x01(\x05R\rmessageOffset\x12#\n" +
	"\rmessage_limit\x18\x03 \x01(\x05R\fmessageLimit\x12!\n" +
	"\ftrace_offset\x18\x04 \x01(\x05R\vtraceOffset\x12\x1f\n" +
	"\vtrace_limit\x18\x05 \x01(\x05R\n" +
	"traceLimit\"S\n" +
	"\x17SessionTimelineToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"\xa0\x02\n" +
	"\x16SessionTimelineMessage\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\ftool_call_id\x18\x05 \x01(\tR\n" +
	"toolCallId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\n" +
	"tool_calls\x18\b \x03(\v2 .hand.v1.SessionTimelineToolCallR\ttoolCalls\"\xb8\x01\n" +
	"\x19SessionTimelineTraceEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\"\xd7\x03\n" +
	"\x1aGetSessionTimelineResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\bmessages\x18\x02 \x03(\v2\x1f.hand.v1.SessionTimelineMessageR\bmessages\x12E\n" +
	"\ftrace_events\x18\x03 \x03(\v2\".hand.v1.SessionTimelineTraceEventR\vtraceEvents\x12*\n" +
	"\x11messages_has_more\x18\x04 \x01(\bR\x0fmessagesHasMore\x12&\n" +
	"\x0ftraces_has_more\x18\x05 \x01(\bR\rtracesHasMore\x126\n" +
	"\x17traces_truncated_before\x18\x06 \x01(\bR\x15tracesTruncatedBefore\x120\n" +
	"\x14first_trace_sequence\x18\a \x01(\x05R\x12firstTraceSequence\x12.\n" +
	"\x13last_trace_sequence\x18\b \x01(\x05R\x11lastTraceSequence\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12!\n" +
	"\ftitle_source\x18\n" +
	" \x01(\tR\vtitleSource2J\n" +
	"\vHandService\x12;\n" +
	"\aRespond\x12\x17.hand.v1.RespondRequest\x1a\x15.hand.v1.RespondEvent0\x012\xca\x06\n" +
	"\x0eSessionService\x12G\n" +
	"\x06Create\x12\x1d.hand.v1.CreateSessionRequest\x1a\x1e.hand.v1.CreateSessionResponse\x12C\n" +
	"\x04List\x12\x1c.hand.v1.ListSessionsRequest\x1a\x1d.hand.v1.ListSessionsResponse\x12>\n" +
	"\x03Use\x12\x1a.hand.v1.UseSessionRequest\x1a\x1b.hand.v1.UseSessionResponse\x12J\n" +
	"\aArchive\x12\x1e.hand.v1.ArchiveSessionRequest\x1a\x1f.hand.v1.ArchiveSessionResponse\x12P\n" +
	"\tUnarchive\x12 .hand.v1.UnarchiveSessionRequest\x1a!.hand.v1.UnarchiveSessionResponse\x12G\n" +
	"\x06Rename\x12\x1d.hand.v1.RenameSessionRequest\x1a\x1e.hand.v1.RenameSessionResponse\x12J\n" +
	"\aCurrent\x12\x1e.hand.v1.CurrentSessionRequest\x1a\x1f.hand.v1.CurrentSessionResponse\x12J\n" +
	"\aCompact\x12\x1e.hand.v1.CompactSessionRequest\x1a\x1f.hand.v1.CompactSessionResponse\x12G\n" +
	"\x06Repair\x12\x1d.hand.v1.RepairSessionRequest\x1a\x1e.hand.v1.RepairSessionResponse\x12M\n" +
	"\x06Status\x12 .hand.v1.GetSessionStatusRequest\x1a!.hand.v1.GetSessionStatusResponse\x12S\n" +
	"\bTimeline\x12\".hand.v1.GetSessionTimelineRequest\x1a#.hand.v1.GetSessionTimelineResponseB2Z0github.com/wandxy/hand/internal/rpc/proto;handpbb\x06proto3"

var (
	file_internal_rpc_proto_hand_proto_rawDescOnce sync.Once
	file_internal_rpc_proto_hand_proto_rawDescData []byte
)

func file_internal_rpc_proto_hand_proto_rawDescGZIP() []byte {
	file_internal_rpc_proto_hand_proto_rawDescOnce.Do(func() {
		file_internal_rpc_proto_hand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_hand_proto_rawDesc), len(file_internal_rpc_proto_hand_proto_rawDesc)))
	})
	return file_internal_rpc_proto_hand_proto_rawDescData
}

var file_internal_rpc_proto_hand_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_rpc_proto_hand_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_internal_rpc_proto_hand_proto_goTypes = []any{
	(RespondEvent_Type)(0),                   // 0: hand.v1.RespondEvent.Type
	(RespondEvent_Channel)(0),                // 1: hand.v1.RespondEvent.Channel
	(RepairSessionRequest_Type)(0),           // 2: hand.v1.RepairSessionRequest.Type
	(*RespondRequest)(nil),                   // 3: hand.v1.RespondRequest
	(*RespondEvent)(nil),                     // 4: hand.v1.RespondEvent
	(*SessionSummary)(nil),                   // 5: hand.v1.SessionSummary
	(*CreateSessionRequest)(nil),             // 6: hand.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),            // 7: hand.v1.CreateSessionResponse
	(*ListSessionsRequest)(nil),              // 8: hand.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),             // 9: hand.v1.ListSessionsResponse
	(*UseSessionRequest)(nil),                // 10: hand.v1.UseSessionRequest
	(*UseSessionResponse)(nil),               // 11: hand.v1.UseSessionResponse
	(*ArchiveSessionRequest)(nil),            // 12: hand.v1.ArchiveSessionRequest
	(*ArchiveSessionResponse)(nil),           // 13: hand.v1.ArchiveSessionResponse
	(*UnarchiveSessionRequest)(nil),          // 14: hand.v1.UnarchiveSessionRequest
	(*UnarchiveSessionResponse)(nil),         // 15: hand.v1.UnarchiveSessionResponse
	(*RenameSessionRequest)(nil),             // 16: hand.v1.RenameSessionRequest
	(*RenameSessionResponse)(nil),            // 17: hand.v1.RenameSessionResponse
	(*CurrentSessionRequest)(nil),            // 18: hand.v1.CurrentSessionRequest
	(*CurrentSessionResponse)(nil),           // 19: hand.v1.CurrentSessionResponse
	(*CompactSessionRequest)(nil),            // 20: hand.v1.CompactSessionRequest
	(*CompactSessionResponse)(nil),           // 21: hand.v1.CompactSessionResponse
	(*RepairSessionRequest)(nil),             // 22: hand.v1.RepairSessionRequest
	(*RepairSessionResponse)(nil),            // 23: hand.v1.RepairSessionResponse
	(*VectorRepairOption)(nil),               // 24: hand.v1.VectorRepairOption
	(*VectorRepairResponse)(nil),             // 25: hand.v1.VectorRepairResponse
	(*GetSessionStatusRequestContext)(nil),   // 26: hand.v1.GetSessionStatusRequestContext
	(*GetSessionStatusRequest)(nil),          // 27: hand.v1.GetSessionStatusRequest
	(*GetSessionStatusResponse)(nil),         // 28: hand.v1.GetSessionStatusResponse
	(*GetSessionTimelineRequest)(nil),        // 29: hand.v1.GetSessionTimelineRequest
	(*SessionTimelineToolCall)(nil),          // 30: hand.v1.SessionTimelineToolCall
	(*SessionTimelineMessage)(nil),           // 31: hand.v1.SessionTimelineMessage
	(*SessionTimelineTraceEvent)(nil),        // 32: hand.v1.SessionTimelineTraceEvent
	(*GetSessionTimelineResponse)(nil),       // 33: hand.v1.GetSessionTimelineResponse
	(*GetSessionStatusResponse_Context)(nil), // 34: hand.v1.GetSessionStatusResponse.Context
	(*timestamppb.Timestamp)(nil),            // 35: google.protobuf.Timestamp
}
var file_internal_rpc_proto_hand_proto_depIdxs = []int32{
	0,  // 0: hand.v1.RespondEvent.type:type_name -> hand.v1.RespondEvent.Type
	1,  // 1: hand.v1.RespondEvent.channel:type_name -> hand.v1.RespondEvent.Channel
	35, // 2: hand.v1.RespondEvent.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 3: hand.v1.CreateSessionResponse.session:type_name -> hand.v1.SessionSummary
	5,  // 4: hand.v1.ListSessionsResponse.sessions:type_name -> hand.v1.SessionSummary
	5,  // 5: hand.v1.UnarchiveSessionResponse.session:type_name -> hand.v1.SessionSummary
	5,  // 6: hand.v1.RenameSessionResponse.session:type_name -> hand.v1.SessionSummary
	35, // 7: hand.v1.CompactSessionResponse.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 8: hand.v1.RepairSessionRequest.type:type_name -> hand.v1.RepairSessionRequest.Type
	24, // 9: hand.v1.RepairSessionRequest.vector:type_name -> hand.v1.VectorRepairOption
	2,  // 10: hand.v1.RepairSessionResponse.type:type_name -> hand.v1.RepairSessionRequest.Type
	25, // 11: hand.v1.RepairSessionResponse.vector:type_name -> hand.v1.VectorRepairResponse
	26, // 12: hand.v1.GetSessionStatusRequest.context:type_name -> hand.v1.GetSessionStatusRequestContext
	34, // 13: hand.v1.GetSessionStatusResponse.context:type_name -> hand.v1.GetSessionStatusResponse.Context
	35, // 14: hand.v1.GetSessionStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	35, // 15: hand.v1.GetSessionStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	35, // 16: hand.v1.SessionTimelineMessage.created_at:type_name -> google.protobuf.Timestamp
	30, // 17: hand.v1.SessionTimelineMessage.tool_calls:type_name -> hand.v1.SessionTimelineToolCall
	35, // 18: hand.v1.SessionTimelineTraceEvent.timestamp:type_name -> google.protobuf.Timestamp
	31, // 19: hand.v1.GetSessionTimelineResponse.messages:type_name -> hand.v1.SessionTimelineMessage
	32, // 20: hand.v1.GetSessionTimelineResponse.trace_events:type_name -> hand.v1.SessionTimelineTraceEvent
	3,  // 21: hand.v1.HandService.Respond:input_type -> hand.v1.RespondRequest
	6,  // 22: hand.v1.SessionService.Create:input_type -> hand.v1.CreateSessionRequest
	8,  // 23: hand.v1.SessionService.List:input_type -> hand.v1.ListSessionsRequest
	10, // 24: hand.v1.SessionService.Use:input_type -> hand.v1.UseSessionRequest
	12, // 25: hand.v1.SessionService.Archive:input_type -> hand.v1.ArchiveSessionRequest
	14, // 26: hand.v1.SessionService.Unarchive:input_type -> hand.v1.UnarchiveSessionRequest
	16, // 27: hand.v1.SessionService.Rename:input_type -> hand.v1.RenameSessionRequest
	18, // 28: hand.v1.SessionService.Current:input_type -> hand.v1.CurrentSessionRequest
	20, // 29: hand.v1.SessionService.Compact:input_type -> hand.v1.CompactSessionRequest
	22, // 30: hand.v1.SessionService.Repair:input_type -> hand.v1.RepairSessionRequest
	27, // 31: hand.v1.SessionService.Status:input_type -> hand.v1.GetSessionStatusRequest
	29, // 32: hand.v1.SessionService.Timeline:input_type -> hand.v1.GetSessionTimelineRequest
	4,  // 33: hand.v1.HandService.Respond:output_type -> hand.v1.RespondEvent
	7,  // 34: hand.v1.SessionService.Create:output_type -> hand.v1.CreateSessionResponse
	9,  // 35: hand.v1.SessionService.List:output_type -> hand.v1.ListSessionsResponse
	11, // 36: hand.v1.SessionService.Use:output_type -> hand.v1.UseSessionResponse
	13, // 37: hand.v1.SessionService.Archive:output_type -> hand.v1.ArchiveSessionResponse
	15, // 38: hand.v1.SessionService.Unarchive:output_type -> hand.v1.UnarchiveSessionResponse
	17, // 39: hand.v1.SessionService.Rename:output_type -> hand.v1.RenameSessionResponse
	19, // 40: hand.v1.SessionService.Current:output_type -> hand.v1.CurrentSessionResponse
	21, // 41: hand.v1.SessionService.Compact:output_type -> hand.v1.CompactSessionResponse
	23, // 42: hand.v1.SessionService.Repair:output_type -> hand.v1.RepairSessionResponse
	28, // 43: hand.v1.SessionService.Status:output_type -> hand.v1.GetSessionStatusResponse
	33, // 44: hand.v1.SessionService.Timeline:output_type -> hand.v1.GetSessionTimelineResponse
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_internal_rpc_proto_hand_proto_init() }
func file_internal_rpc_proto_hand_proto_init() {
	if File_internal_rpc_proto_hand_proto != nil {
		return
	}
	file_internal_rpc_proto_hand_proto_msgTypes[0].OneofWrappers = []any{}
	file_internal_rpc_proto_hand_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_hand_proto_rawDesc), len(file_internal_rpc_proto_hand_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_rpc_proto_hand_proto_goTypes,
		DependencyIndexes: file_internal_rpc_proto_hand_proto_depIdxs,
		EnumInfos:         file_internal_rpc_proto_hand_proto_enumTypes,
		MessageInfos:      file_internal_rpc_proto_hand_proto_msgTypes,
	}.Build()
	File_internal_rpc_proto_hand_proto = out.File
	file_internal_rpc_proto_hand_proto_goTypes = nil
	file_internal_rpc_proto_hand_proto_depIdxs = nil
}
