package goreadability

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestFormatSource_AppliesCanonicalAndSemanticSpacing(t *testing.T) {
	source := []byte(`package sample
import "sync"
func work(mu *sync.Mutex, value string) string {
if value == "" { return "" }
if value == "skip" { return "" }
mu.Lock()
defer mu.Unlock()
for value == "again" { value = "done" }
return value
}
`)

	formatted, generated, err := formatSource("sample.go", source)
	require.NoError(t, err)
	require.False(t, generated)
	require.Equal(t, `package sample

import "sync"

func work(mu *sync.Mutex, value string) string {
	if value == "" {
		return ""
	}
	if value == "skip" {
		return ""
	}

	mu.Lock()
	defer mu.Unlock()

	for value == "again" {
		value = "done"
	}

	return value
}
`, string(formatted))
}

func TestFormatSource_PreservesCommentsAndExistingSpacing(t *testing.T) {
	source := []byte(`package sample

func work(value string) string {
	if value == "" {
		return ""
	}
	// Keep this comment attached to the assignment.
	value = "ready"

	return value
}
`)

	formatted, _, err := formatSource("sample.go", source)
	require.NoError(t, err)
	require.Equal(t, string(source), string(formatted))
}

func TestFormatSource_DoesNotTreatMidFunctionConditionAsGuardSection(t *testing.T) {
	source := []byte(`package sample

func work(value string) string {
	value = "ready"
	if value == "skip" {
		return ""
	}
	value = "done"
	return value
}
`)

	formatted, _, err := formatSource("sample.go", source)
	require.NoError(t, err)
	require.Equal(t, string(source), string(formatted))
}

func TestFormatPaths_CheckAndWriteModes(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	require.NoError(t, os.WriteFile(path, []byte("package sample\nfunc value() int { if true { return 1 }; return 0 }\n"), 0o640))

	checked, err := FormatPaths([]string{root}, FormatOptions{})
	require.NoError(t, err)
	require.Equal(t, 1, checked.Files)
	require.Equal(t, []string{path}, checked.Changed)
	unchanged, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Contains(t, string(unchanged), "; return")

	written, err := FormatPaths([]string{root}, FormatOptions{Write: true})
	require.NoError(t, err)
	require.Equal(t, []string{path}, written.Changed)
	info, err := os.Stat(path)
	require.NoError(t, err)
	require.Equal(t, os.FileMode(0o640), info.Mode().Perm())

	rechecked, err := FormatPaths([]string{root}, FormatOptions{})
	require.NoError(t, err)
	require.Empty(t, rechecked.Changed)
}

func TestFormatPaths_SkipsExcludedAndGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(root, "vendor", "dependency"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, "vendor", "dependency", "vendor.go"), []byte("package dependency\nfunc value(){return}\n"), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(root, "generated.go"), []byte("// Code generated by test. DO NOT EDIT.\npackage sample\nfunc value(){return}\n"), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(root, "schema.pb.go"), []byte("package sample\nfunc value(){return}\n"), 0o600))

	result, err := FormatPaths([]string{root}, FormatOptions{})
	require.NoError(t, err)
	require.Equal(t, 1, result.Files)
	require.Empty(t, result.Changed)

	result, err = FormatPaths([]string{root}, FormatOptions{IncludeGenerated: true})
	require.NoError(t, err)
	require.Equal(t, []string{filepath.Join(root, "generated.go")}, result.Changed)
}

func TestFormatPaths_RejectsInvalidPathsAndSource(t *testing.T) {
	_, err := FormatPaths([]string{" "}, FormatOptions{})
	require.EqualError(t, err, "codebase path is required")

	_, err = FormatPaths([]string{filepath.Join(t.TempDir(), "missing")}, FormatOptions{})
	require.ErrorContains(t, err, "inspect")

	path := filepath.Join(t.TempDir(), "invalid.go")
	require.NoError(t, os.WriteFile(path, []byte("package"), 0o600))
	_, err = FormatPaths([]string{path}, FormatOptions{})
	require.ErrorContains(t, err, "format")
}

func TestFormattingPredicates(t *testing.T) {
	require.True(t, isExcludedDirectory(".git"))
	require.True(t, isExcludedDirectory("testdata"))
	require.False(t, isExcludedDirectory("internal"))
	require.True(t, isGoSourceFile("main.go"))
	require.False(t, isGoSourceFile("main.pb.go"))
	require.False(t, isGoSourceFile("README.md"))
	require.True(t, isSingleWhitespaceLine([]byte("\n\t")))
	require.False(t, isSingleWhitespaceLine([]byte("\n\n\t")))
	require.False(t, isSingleWhitespaceLine([]byte(" // comment\n\t")))
}
